// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

// initiate character arrays for usage later
var alphabetLower = ["a","b","b","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];
var alphabetUpper = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];
var numbers = [0, 1, 2, 3, 4, 5, 6, 7, 9, 9];
var special = ["~","`","!","@","#","$","%","^","&","*","(",")"," ","\'", "\"","-","+","=","_","\\","]","[","<",">","?","{","}","|", ":",";", ","];

// nested array of all 4 arrays
 var totalArr = [["a","b","b","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"], ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"], [0, 1, 2, 3, 4, 5, 6, 7, 9, 9], ["~","`","!","@","#","$","%","^","&","*","(",")"," ","\'", "\"","-","+","=","_","\\","]","[","<",">","?","{","}","|", ":",";", ","]];

// initate booleans for later when user chooses to include characters or not
var low = false;
var up = false;
var num = false;
var spec = false;

// function generates password
function generatePassword() {
  // initialize empty string for password
  let password ="";
  let length = prompt("how long would you like the password to be?");

  // conditional to alert the user if the size isn't between 8 or 128
  if(length < 8 || length > 128) {
    alert("please choose a length BETWEEN 8 and 128")
    generatePassword();
  } else {
    var newTotalArr = chooseChar();

    // generates password by concatenating strings together based on a random number generated byt the length provided by the user
    for(let i = 0; i <= length; i++) {
      let x = Math.floor(Math.random() * newTotalArr.length);
      password = password + newTotalArr[x];
    }
  }

  return password;
}


// function determines what characters are used for the password based on user input
function chooseChar() {
  // initialize empty array
  let newTotalArr = [];

  // confirm user input on what characters to include
  low = confirm("Would you like lowercase characters?");
  up = confirm("Would you like uppercase characters?");
  num = confirm("would you like numbers?");
  spec = confirm("Would you like special characters?");

  // check if at least one character set was included
  if(up == false && low == false && spec == false && num == false) {
    alert("Please select at least one type")
    chooseChar();
  } else {
    // create an array of boolean values to loop through
    let boolarr = [low, up, num, spec];

    // concatenates character array to a new array to use when generating the password
    // based on the index of the boolean array, we determine what characters are included
    for (let k = 0; k <= boolarr.length; k++) {
      if(boolarr[k]) {
        newTotalArr = newTotalArr.concat(totalArr[k]);
        console.log(newTotalArr);
      }
    }
  }
  return newTotalArr;
}
